database:
  host: localhost
  username: root
  password: ""
  port: 3306
  databasename: hu1
  sql_query: SELECT * FROM sw
http:
  baseurl: http://192.168.43.228/phpwind/phpwind/index.php
  port: 80
  timeout: 1.0
mail:
  mail_host: smtp.qq.com
  mail_user: 3471648281@qq.com
  mail_pass :
  mail_port: 25
  sender: 3471648281@qq.com
  receiver: 670339851qq.com
  subject: python
  content: "All interface test has been complited\nplease read the report file about the detile of result in the attachment."
  testuser: Someone
  on_off: 1

